baseURL: https://awethon.github.io/
languageCode: en-us
title: Awethon's Page
theme: PaperMod

enableRobotsTXT: true
minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

params:
  social: true
  profileMode:
    enabled: true
    title: "Aleksey Polovinkin"
    subtitle: "Scala developer and Functional Programming enthusiast\n\nWanna be Principal Software Engineer\n\nAlways open to new opportunities"

  socialIcons:
    - name: "Github"
      url: "https://github.com/awethon/"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/awethon/"
    - name: "Telegram"
      url: "https://telegram.me/awethon/"
    - name: "Email"
      url: "mailto:awethon@gmail.com"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  editPost:
    URL: "https://github.com/Awethon/awethon.github.io/blob/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  ShowShareButtons: true